# Generated by Django 5.1.4 on 2025-01-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
